server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ip}:3306/unicollect
    username: root
    password: 12345678
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis: { mapper-locations: classpath*:cn/kiana/unic/mapper/*.xml,
           type-aliaiase-package: cn.kiana.unic.pojo }


ip: localhost